---

- name: Network Infos 
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: routers
  become: true
  become_method: enable

  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world
    delegate_to: 127.0.0.1

  - name: run the command 'ip route print'
    routeros_command:
      commands: /ip route print
    register: output1

  - name: print result
    debug:
       var: output1.stdout_lines  
