---

- name: Network Infos 
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: routers
  become: true
  become_method: enable

  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world
  
