- name: Check if reacheable
  local_action: ansible.builtin.command ping -c 3 {{  inventory_hostname }}
  ignore_errors: true
  register: pingResult

- name: Recupere model et nom
  community.routeros.facts:
  when: pingResult.stdout.find(' 100% packet loss') == -1

- name: Display infos
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} a pour model {{ ansible_net_model }} et pour nom {{ ansible_net_hostname }}: "
  when: pingResult.stdout.find(' 100% packet loss') == -1

- name: Genere le fichier de backup
  routeros_command:
    commands: export file=bkp
  when: pingResult.stdout.find(' 100% packet loss') == -1

- name: Vérifie l'existance du dossier en local
  local_action: command python3 /home/ansible/scripts/verifyBackupDir.py {{ ansible_net_model }}
  when: pingResult.stdout.find(' 100% packet loss') == -1

- name: forgetting known_hostssh
  when : pingResult.stdout.find(' 100% packet loss') == -1
  local_action: shell ssh-keygen -f "/root/.ssh/known_hosts" -R "{{  inventory_hostname }}"

- name: download Backup
  when : pingResult.stdout.find(' 100% packet loss') == -1
  local_action: shell sshpass -p {{ ansible_password }} scp -o StrictHostKeyChecking=no {{ ansible_user }}@{{  inventory_hostname }}:/bkp.rsc /home/ansible/backupsMicrotiks/{{ ansible_net_model }}/ 

- name: rename Backup
  when : pingResult.stdout.find(' 100% packet loss') == -1
  local_action: shell mv /home/ansible/backupsMicrotiks/{{ ansible_net_model }}/bkp.rsc /home/ansible/backupsMicrotiks/{{ ansible_net_model }}/{{ ansible_net_hostname }}{{ lookup('pipe', 'date +%Y-%m-%d') }}.txt

- name: Supprime le fichier sur le routeur
  routeros_command:
    commands: /file remove bkp.rsc
  when: pingResult.stdout.find(' 100% packet loss') == -1
