- name: run the command 'export'
  routeros_command:
    commands: /export
  register: output1

- name: Backup
  ansible.builtin.shell: >-
    echo  {{ output1.stdout }} > "{{ backup_dir }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
  when: output1
  delegate_to: 127.0.0.1

